config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'  
  resources :users, except: [:new]
  get 'login/show_signup', to: 'users#new'
  get 'login/show_login', to: 'sessions#new'
  post 'login/show_login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'


  get 'products/show_arrivals', to: 'products#show_arrivals'
  get 'products/show_features', to: 'products#show_features'

  post 'products/show_arrivals', to: 'users#add_to_cart'
  post 'products/show_features', to: 'users#add_to_cart'

  delete '/remove_from_cart', to: 'users#remove_from_cart'

  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  
  before_save :format_email
  before_create :encrypt_password
  has_many :products
  validates :first_name, presence: true,length: {minimum: 3, maximum:25}
  validates :last_name, presence: true, length: {minimum: 3, maximum:25}
  VALID_EMAIL_REGEX= /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum:125} , uniqueness: {case_sensitive: false} ,format: {with: VALID_EMAIL_REGEX}
  
  require 'bcrypt'
  has_secure_password

  def encrypt_password
    self.password_digest= BCrypt::Password.create(self.password)
  end

  def format_email
    self.email= email.downcase
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id] 
  end
  
  def logged_in?
    !!current_user
  end

  def require_user

    if !logged_in?
      flash[:alert] = "You must be logged in to perform that action." 
      redirect_to login_show_login_path
    end
    
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
    redirect_to current_user if logged_in?
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def show_arrivals
    @arrivals =Product.where(:ProductCategory => "arrival").paginate(page: params[:page], per_page: 3)
  end

  def show_features
    @features = Product.where(ProductCategory: "features").paginate(page: params[:page], per_page: 2)
  end

 
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase) if !params[:session][:email].nil?

    if user && user.authenticate(params[:session][:password])
      session[:user_id]= user.id
      flash[:notice] = "Logged in successfully."
      redirect_to user
    
    else
      flash.now[:alert] = "Something was wrong with your credentials."
      render 'new'
    end

  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out successfully."
    redirect_to  root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show,:edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update]
  before_action :require_same_user, only: [:edit, :update, :destroy]
    

  def index
    @users= User.all.paginate(page: params[:page], per_page: 3)
  end

  def new 
    @user= User.new
  end

  def create 
    
    @user=User.new(user_params)

    if  @user.save
      session[:user_id] = @user.id
      flash[:notice] ="#{(current_user.first_name + ' ' + current_user.last_name).capitalize()} has been successfully created."
      redirect_to user_path(@user)
    else
      render 'new'
    end

  end
  
  def show
   
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "#{(current_user.first_name + ' ' + current_user.last_name).capitalize()} Info has been updated"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def destroy
    @user.destroy
    session[:user_id] =  nil if @user ==current_user
    flash[:notice] = "The Furnico account #{(@user.first_name + @user.last_name).capitalize()} has been deleted and cart items have been cleared."
    redirect_to users_path 
  end

  

  def add_to_cart
    @add_to_cart_product= Product.find_by(:id => params[:product_id])
    if logged_in?
      current_user.products << @add_to_cart_product
      flash[:alert] = "#{@add_to_cart_product.ProductName} has been added to your cart."
      redirect_to user_path(current_user)
    else
      # current user is nil and not logged in
      flash[:notice ] = "Please login to add items to cart."
      redirect_to login_show_login_path

    end
  end

  def remove_from_cart
    @remove_from_cart_product= Product.find_by(:id => params[:product_id])
    if logged_in?
      current_user.products.delete(@remove_from_cart_product.id)
      flash[:alert] = "#{@remove_from_cart_product.ProductName} has been removed from your cart."
      redirect_to user_path(current_user)
    else
      flash[:notice ] = "Please login to remove items from cart."
      redirect_to login_show_login_path
    end
  end
  
  private 
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email , :password )
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = "You can edit your own account."
      redirect_to @user
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/all.css">

<!-- Footer -->
<footer id= "sticky-footer" class="fixed-bottom flex-shrink-0  bg-dark text-center text-white mt-5 font-small" >
  <!-- Grid container -->
  <div class="container p-4" >
    <!-- Section: Social media -->
    <section class="mb-4">
      <!-- Github -->
      <a class="btn btn-outline-light btn-floating m-1" href="https://github.com/VaibhavGupta-Oncehub" role="button"
        ><i class="fab fa-github"></i
      ></a>
    </section>
    <!-- Section: Social media -->

    <!-- Section: Form -->
    <section class="">
      <form action="">
        <!--Grid row-->
        <div class="row d-flex justify-content-center">
          <!--Grid column-->
          <div class="col-auto">
            <p class="pt-2">
              <strong>Sign up for our newsletter</strong>
            </p>
          </div>
          <!--Grid column-->

          <!--Grid column-->
          <div class="col-md-5 col-12">
            <!-- Email input -->
            <div class="form-outline form-white mb-4">
              <input type="email" id="form5Example21" class="form-control" />
              <label class="form-label" for="form5Example21">Email address</label>
            </div>
          </div>
          <!--Grid column-->

          <!--Grid column-->
          <div class="col-auto">
            <!-- Submit button -->
            <button type="submit" class="btn btn-outline-light mb-4">
              Subscribe
            </button>
          </div>
          <!--Grid column-->
        </div>
        <!--Grid row-->
      </form>
    </section>
    <!-- Section: Form -->

    <!-- Section: Links -->
    <section class="">
      <!--Grid row-->
      <div class="row justify-content-center">
        <!--Grid column-->
        <div class="col-lg-3 col-md-6 mb-4 mb-md-0 ">
          <h5 class="text-uppercase ">Information</h5>

          <ul class="list-unstyled mb-0">
            <li >
              <a href="#!" class="text-white">About Us</a>
            </li>
            <li>
              <a href="#!" class="text-white">Contact Us</a>
            </li>
          </ul>
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
          <h5 class="text-uppercase">My Accounts</h5>

          <ul class="list-unstyled mb-0">
            <li>
              <a href="#!" class="text-white">My User Account</a>
            </li>
            <li>
              <a href="#!" class="text-white">My Orders</a>
            </li>
            <li>
              <a href="#!" class="text-white">My Cart</a>
            </li>
          </ul>
        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->
    </section>
    <!-- Section: Links -->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->

  <div class="h-divider">
    <div class="shadow"></div>
    <div class="text2"><img src="https://t1.gstatic.com/images?q=tbn:ANd9GcQsmMfybMIwoE5etmOIAuvnFWdfv_8C1Bq15urJFqwhhI55FyYNP2YuUA" /></div>
    <div class="text-center p-3 mt-2">
    © 2022 Copyright:
    <a class="text-white" href="#!">Furnico.com</a>
  </div>
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark ">
  <div class="container-fluid ">
    <strong class="navbar-brand"id=logo href= <%link_to root_path%> >Furnico | Personal Furniture Destination</strong>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse " id="navbarSupportedContent">
      <ul class="navbar-nav mx-auto mb-2 mb-lg-0">
        <li class="nav-item ">
          <%= link_to "Home" , root_path , class:"nav-link active"%>
        </li>
        <li class="nav-item ">
          <%=link_to "Furnico Community",users_path, class:"nav-link active" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Furniture
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><%=link_to "New Arrival", products_show_arrivals_path,class: "dropdown-item"%></li>
            <li><%=link_to "Features", products_show_features_path,class: "dropdown-item"%></li>
          </ul>
        </li>
        
        <% if logged_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%="(Admin)" if current_user.admin?%> Profile[ <%= (current_user.first_name + ' ' + current_user.last_name).capitalize()%> ]
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><%=link_to "View Your Profile",user_path(current_user),class: "dropdown-item"%></li>
              <li><%=link_to "Edit Your Profile", edit_user_path(current_user),class: "dropdown-item"%></li>
              <li><%=link_to "Delete Your Profile", user_path(current_user),class: "dropdown-item bg-danger text-white", method: :delete , data: {confirm: "Are you sure you want to delete #{(current_user.first_name + ' ' + current_user.last_name).capitalize()}'s Furnico Account?" }%></li>
            </ul>
          </li>
          <li class="nav-item ">
            <%=link_to "Logout",logout_path, class:"nav-link active", method: :delete %>
          </li>
        <% else %>
          <li class="nav-item ">
            <%=link_to "Login",login_show_login_path, class:"nav-link active" %>
          </li>
          <li class="nav-item ">
            <%=link_to "Signup",login_show_signup_path, class:"nav-link active" %>
          </li>
        <%end%>
      </ul>
      <form class="d-flex mt-2 ">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class=" btn btn-outline-light h-50" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Furnico</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id= "nav"><%= render "layouts/navbar"%></div>
    <div class="container">
      <div id= "main">
      <% flash.each do |name, message|%>
        <div class="alert alert-success alert-dismissible fade show mt-5" role="alert">
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          <h4 class="display-4  m-5 tr text-center"><%=message%></h2>
        </div>
      <%end%>
      <%= yield %>
      </div>
      <div id="footer"> <%= render "layouts/footer"%> </div> 
    </div>
  </body>
</html>

app/views/pages/_jumbotron_cards.html.erb
 <div id = "homepage_cards" class="container mt-5 mb-10">
    <h1 class="display-1 color: black text-center"> Why you'll love furnico ? </h1>
    <div class="row row-cols-1 row-cols-md-2 g-4 mt-4 mb-5">
      <div class="col">
        <div class="card">
          <%= image_tag("heart.png", :class => "mx-auto img-circle mt-3 mb-3 ")%>
          <div class="card-body">
            <h5 class="card-title">Elegant Designs and Products</h5>
            <p class="card-text">We provide a range of furnitures with a variety of themes and designs.</p>
          </div>
        </div>
      </div>
      <div class="col">
        <div class="card">
          <%= image_tag("delivery.png", :class => "mx-auto img-circle mt-3 mb-3")%>
          <div class="card-body">
            <h5 class="card-title">Fast Home Delivery</h5>
            <p class="card-text">Our logistics take cares of your furniture and its delivery with high standards.</p>
          </div>
        </div>
      </div>
      <div class="col">
        <div class="card">
          <%= image_tag("cheap.png", :class => "mx-auto img-circle mt-3 mb-3")%>
          <div class="card-body">
            <h5 class="card-title">Affordable Pricing</h5>
            <p class="card-text">Get your furniture at best prices with furnico.</p>
          </div>
        </div>
      </div>
      <div class="col">
        <div class="card">
         <%= image_tag("furnitures.png", :class => "mx-auto img-circle mt-3 mb-3")%>
          <div class="card-body">
            <h5 class="card-title">Exceptionally Durable</h5> 
            <p class="card-text">Our furnitures are crafted with best practices and raw materials.</p>
      </div>
    </div>
  </div>

app/views/pages/_jumbotron_image.html.erb
<div class="jumbotron text-white jumbotron-image shadow p-5 text-center bg-image rounded-3" style="background-image: url(/assets/homepage_image1.jpg); height: 600px">
    <div class="mask" style="background-color: rgba(0, 0, 0, 0.6); height: 300px ">
      <div class="d-flex justify-content-center align-items-center h-100">
        <div class="text-white">
          <h1 class="mb-3">Welcome To Furnico </h1>
          <h4 class="mb-3">Now shop for your personal furniture with a human touch.</h4>
          <%= link_to "Show Now", products_show_arrivals_path, class: "btn btn-outline-light btn-lg"%>
        </div>
      </div>
    </div>
  </div>

app/views/pages/home.html.erb
<div class="container py-5">
  
  <%= render 'jumbotron_image'%>

  <%= render 'jumbotron_cards'%>

</div>

app/views/products/show_arrivals.html.erb
<h1 class="display-1 color: black text-center mt-5" > New Arrivals Furniture </h1>

<div class="flickr_pagination">
  
  <%= will_paginate @arrivals, :container=> false %>

</div>
<% @arrivals.each do |arrival|%>
  <div class="card mt-5 mb-5">
    <%= image_tag(arrival.ImageName, :class => "mx-auto img-circle mt-3 mb-3 ")%>
    <div class="card-body">
      <h5 class="card-title"><%= arrival.ProductName %></h5>
      <p class="card-text"><%= arrival.ProductDescription%></p>
      <p class="card-text">₹- <%= arrival.ProductPrice%></p>
    </div>
    <div class="text-white text-center mb-5">
      <%= form_with(url:products_show_arrivals_path , method: "post",local: true) do |f| %>
        <%= f.button "Add to Cart" ,class: "btn btn-success w-25", name:"product_id",value: arrival.id %>
      <%end%>
    </div>
    <div class="card-footer">
      <small class="text-muted">Last updated <%= time_ago_in_words(arrival.updated_at)%> ago.</small>
    </div>
  </div>
<% end %>


<div class="text-white text-center">
  <%= link_to "Feature Furnitures", products_show_features_path, class: "btn btn-primary btn-lg"%>
</div>

app/views/products/show_features.html.erb
<h1 class="display-1 color: black text-center mt-5" > Features Furniture </h1>

<div class="flickr_pagination">
  <%= will_paginate @features, :container=> false %>
</div>

<% @features.each do |feature|%>
  <div class="card mt-5 mb-5">
    <%= image_tag(feature.ImageName, :class => "mx-auto img-circle mt-3 mb-3 ")%>
    <div class="card-body">
      <h5 class="card-title"><%= feature.ProductName%></h5>
      <p class="card-text"><%= feature.ProductDescription%></p>
      <p class="card-text">₹- <%= feature.ProductPrice%></p>
    </div>
    <div class="text-white text-center mb-5">
      <%= form_with(url:products_show_arrivals_path , method: "post",local: true) do |f| %>
        <%= f.button "Add to Cart" ,class: "btn btn-success w-25", name:"product_id",value: feature.id %>
      <%end%>
    </div>
    <div class="card-footer">
      <small class="text-muted">Last updated <%= time_ago_in_words(feature.updated_at)%> ago .</small>
    </div>
  </div>
<% end %>
<div class="text-white text-center">
  <%= link_to "New Arrivals Furniture", products_show_arrivals_path, class: "btn btn-primary btn-lg"%>
</div>

app/views/users/_shopping_cart.html.erb
<h3 class=" fw-bold mb-5 text-black text-center justify-content-center">Shopping Cart</h3>

<section class="h-100">
  <div class="container h-100 w-auto">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-10">
        <% if !@user.products.empty? %>
          <% @user.products.each do |product|%>
            <div class="card rounded-3 mb-4 w-auto h-auto">
              <div class="card-body p-4">
                <div class="row d-flex justify-content-between align-items-center">
                  <div class="col-md-2 col-lg-2 col-xl-2">
                  <%= image_tag(product.ImageName, :class => "mx-auto img-fluid rounded-3 mt-3 mb-3 ")%>
                  </div>
                  <div class="col-md-3 col-lg-3 col-xl-3 w-50">
                    <p class="lead fw-bold mb-2"><%=product.ProductName%></p>
                    <p><span class="text-muted text-dark"><%= product.ProductDescription%></p>
                  </div>
                  <div class="col-md-3 col-lg-2 col-xl-2 offset-lg-1">
                    <h5 class="mb-0">₹- <%=product.ProductPrice%></h5>
                  </div>
                  <div class="text-center">
                    <%= form_with(url:remove_from_cart_path , method: "delete",local: true, data: {confirm: "Do you want to delete #{product.ProductName}?"}) do |f| %>
                      <%= f.button "Remove Item" ,class:"text-white btn btn-danger" ,name:"product_id",value: product.id  %>
                    <%end%>
                  </div>
                </div>
              </div>
            </div>
          <%end%>
          <div class="card mb-4">
            <div class="card-body justify-content-center">
              <div class="row-md-4 text-center">
                <div class="card mb-4 text-center">
                  <div class="card-header py-3">
                    <h5 class="mb-0">Summary</h5>
                  </div>
                  <div class="card-body">
                    <ul class="list-group list-group-flush">
                      <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 pb-0">
                        Products
                        <span><%= @user.products.count%></span>
                      </li>
              
                      <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 mb-3">
                        <div>
                          <strong>Total amount</strong>
                        </div>
                        <span><strong>₹- <%= @user.products.sum(:ProductPrice) %></strong></span>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="card text-center">
            <div class="card-body m-3">
              <button type="button" class="btn btn-success btn-block btn-lg btn-outline-dark ">Proceed to Pay</button>
              <%=link_to "Continue Shopping",products_show_arrivals_path, class:"btn btn-info btn-block btn-lg btn-outline-dark m-5"%>
            </div>
          </div>

        <%else%>
          <div class="text-center">
            <div class="container-fluid mt-100">
              <div class="row">
                  <div class="col-md-12">
                      <div class="card">
                          <div class="card-header">
                              <h5>Cart</h5>
                          </div>
                          <div class="card-body cart">
                              <div class="col-sm-12 empty-cart-cls text-center m-10"> <img src="https://i.imgur.com/dCdflKN.png" width="130" height="130" class="img-fluid mb-4 mr-3">
                                <h3><strong>Your Cart is Empty</strong></h3>
                                <%=link_to "Continue Shopping",products_show_arrivals_path, class:"btn btn-info btn-block btn-lg btn-outline-dark m-5"%>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
            </div>
          </div>
        <%end%>
      </div>
    </div>
  </div>
</section>

app/views/users/edit.html.erb
<h1 id= "community" class="display-1  m-5 tr text-center"> Welcome to Edit <%=(@user.first_name + ' ' + @user.last_name).capitalize()%>'s Furnico Account </h1>

<% if @user.errors.any? %>
  
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h2 class="alert-heading"> Please resolve the following errors</h2>
    <ul class="mb-5">
      <% @user.errors.full_messages.each do |message| %>
        <li> <%= message %> </li>
      <%end%>
    </ul>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

<%= form_with(model:@user,  local: true) do |f| %>
  <div class="container-fluid justify-content-center">
    <div class="card card0 border-2 mx-auto mt-10">
      <div class="row d-flex ">
        <div class="col-lg-6">
          <div class="card1 bg-light pb-5">
            <div class="row px-3 justify-content-center mt-4 mb-5"> <img src="https://i.imgur.com/ucirQQf.png" class="image"> </div>
            <div class="row px-3 text-center justify-content-center">
              <h4>Furnico | Your Personal Furniture Destination.</h4>
            </div>
          </div>
        </div>
        <div class="col-lg-6">
          <div class="card2 card border-0 px-4 py-5">
            <h3 class="mb-1">Edit Your Furnico account.</h3>
            <div class="row px-3">
              <div class="line"></div>
              <div class="line"></div>
            </div>
            <div class="row mt-3">
              <div class="col-md-6">
                <label class="mb-0">
                  <h6 class="mb-0 text-sm">First Name</h6>
                </label>
                <%= f.text_field :first_name %>
              </div>
              <div class="col-md-6">
                <label class="mb-0">
                  <h6 class="mb-0 text-sm">Last Name</h6> 
                </label>
                <%= f.text_field :last_name %>
              </div>
            </div>
            <div class="row px-3">
              <label class="mb-0">
                <h6 class="mb-0 text-sm">Email Address</h6>
              </label>
              <%= f.email_field :email %>
            </div>
            <div class="row px-3">
              <label class="mb-0">
                <h6 class="mb-0 text-sm">Password</h6>
              </label>
              <%= f.password_field :password %>
            </div>
            <div class="row mb-4 justify-content-center">
              <div class="col-md-5"> 
                <%= f.submit "Update Account",class:"btn btn-blue text-center mb-1", data: { confirm: "Are you sure?" } %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/index.html.erb
<h2 id= "community" class="display-2  m-5 mb-5 tr text-center"> Welcome to the Furnico Community</h2>

<div class="flickr_pagination">
  
  <%= will_paginate @users, :container=> false %>

</div>
<div class="container">
  <% @users.each do |user| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            <%=link_to (user.first_name + ' ' + user.last_name).capitalize(), user_path(user) %>            
          </div>
          <div class="card-body">
            <h5 class="card-title">
            <div class="d-flex flex-column align-items-center text-center">
              <img src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="Admin" class="rounded-circle" width="150">
          </div>
            </h5>
            <p class="card-text"><%= pluralize(user.products.count, "products") %></p>
            <%= link_to "View profile", user, class: "btn btn-outline-success" %>
            <% if logged_in?%>
              <% if (user == current_user || current_user.admin?)%>
                <%= link_to "Edit profile", edit_user_path(user), class: "btn btn-outline-info" %>
              <% end %>
               <% if (user == current_user ||current_user.admin?)%>
                <%= link_to "Delete profile",user_path(user), method: :delete, class: "btn btn-outline-danger", data:{ confirm: "Are you sure you want to delete #{(user.first_name + ' ' + user.last_name).capitalize()} 's profile ?"} %>
              <% end %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Joined <%= time_ago_in_words(user.created_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<h1 id= "community" class="display-1  m-5 tr text-center"> <%=(@user.first_name + ' ' + @user.last_name).capitalize()%>'s Furnico Account</h1>

<div class="card mt-5">
  <div id="user_profile" class="container mt-5 mb-5">
    <div class="main-body">
      <div class="row gutters-sm">
        <div class="col-md-4 mb-3">
          <div class="card ">
            <div class="card-body">
              <div class="d-flex flex-column align-items-center text-center">
                <img src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="Admin" class="rounded-circle" width="150">
                <div class="mt-3">
                  <h4><%= (@user.first_name + ' ' + @user.last_name).capitalize() %></h4><hr>
                  <% if logged_in? && (@user == current_user || current_user.admin?) %>
                    <%=link_to "Delete Your Profile", user_path(@user),class: "btn btn-danger", method: :delete , data: {confirm: "Are you sure you want to delete #{(@user.first_name + ' ' + @user.last_name).capitalize()}'s Furnico Account?" }%>
                  <%end%>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-8">
          <div class="card mb-3">
            <div class="card-body">
              <div class="row">
                <div class="col-sm-3">
                  <h6 class="mb-0">First Name</h6>
                </div>
                <div class="col-sm-9 text-secondary">
                  <%= (@user.first_name).capitalize() %>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <h6 class="mb-0">Last Name</h6>
                </div>
                <div class="col-sm-9 text-secondary">
                  <%= (@user.last_name).capitalize() %>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <h6 class="mb-0">Email</h6>
                </div>
                <div class="col-sm-9 text-secondary">
                  <%= @user.email %>
                </div>
              </div>
              <hr>
              <div class="row mt-5 mb-4">
                <div class="col-sm-12">
                  <% if logged_in? && (@user == current_user || current_user.admin?) %>
                    <%= link_to "Edit Details",edit_user_path(@user),class: "btn btn-info"%>
                  <%end%>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <hr><hr>
      <div id="shopping cart">
        <%= render 'shopping_cart' if logged_in? && (@user== current_user || current_user.admin?)%>
      </div>
    </div> 
</div>
</div>